//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThaiHoaiDu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spham
    {
        public int MaSanPham { get; set; }
        public string TenSanPham { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public string Anh { get; set; }
        public Nullable<bool> PhanBiet { get; set; }
    }
}
